### PR TITLE
No more suggest LegionBoard as a system

### PR DESCRIPTION
**Pull request by AltNico**
Today, I've officially declared LegionBoard end of life.

After talking with @raphaelm two months ago I realized that LegionBoard won't have a sustainable future with active development. I don't want to let more and more schools on search for an open and free alternative run into this dead end, but rather inform them transparently what LegionBoard is currently about. This includes removing suggestions on installing LegionBoard on this site.

Nevertheless, I would like to thank @johan12345 for the past years of collaboration. It was a pleasure to work with you and I've learned a lot of it. I wish you the best for Vertretungsplan.app and all your other projects!

Related commits:

* [legionboard/website@699a01509](https://gitlab.com/legionboard/website/commit/699a01509642b1429228f14f66504646de38d348)
* [legionboard/heart@3da8f81e](https://gitlab.com/legionboard/heart/commit/3da8f81e022aeba402c8f20f366eeeede655d626)
* [legionboard/eye@b1e1e647](https://gitlab.com/legionboard/eye/commit/b1e1e647d3adf2486480d1eb1d5f8f1cd5d790b7)
* [legionboard/kiss@75c4bf0d](https://gitlab.com/legionboard/kiss/commit/75c4bf0d1adebb30415cca09ba9e7f6c02556edc)

### CODE REVIEW

**Comment by AltNico** [comment]
Note that the Lichtenberg-Oberstufengymnasium in Bruchköbel will continue to use LegionBoard as their system. Therefore, it would be nice if it could stay in the Vertretungsplan app.

**Comment by raphaelm** [comment]
I'm sorry to see this go, but fully understand the reasoning. Thanks for your hard work creating and maintaining it up to now! <3

**Comment by johan12345** [comment]
Thank you very much for your work!

**Comment by johan12345** [comment]
And of course, we will keep the LegionBoard parser in the app for all schools that continue to use it (on their own risk)

**Pull request merged**
